Use alternative DNS resolver for initial setup (fixes #21)
dnsimple/coredns-dnsimple pull request #25
Opened 2023-08-10 11:43 UTC by wilson-dnsimple

Use a well known DNS resolver for HTTP requests during the initial setup phrase to ensure they don't fail if the CoreDNS server itself is used as the system resolver, as it won't be ready at that time. Fixes #21

2023-08-15 22:39 UTC, AGS4NO approved these changes

2023-10-17 03:24 UTC, DXTimer requested changes

2024-01-18 10:27 UTC, weppos commented
Planned to be completed by next week.

2024-01-18 16:34 UTC, DXTimer approved these changes

2024-01-18 16:57 UTC, merged